mealDict = {1:"Breakfast", 2:"Lunch", 3:"Dinner", 4:"Other"}
cuisineDict = {1:"African", 2:"British", 3:"Chinese", 4:"French", 5:"Fast Food", 6:"Indian", 7:"Italian", 8:"Japanese", 9:"Korean", 10:"Lebanese", 11:"Mexican", 12:"Turkish", 13:"Other"}
mealList = {"Breakfast":{"The Spon Gate", "Rix's Bombay Cafe Bar", "The Ocean", "Cafe Rouge", "Millie's Kitchen", "Horse and Jockey", "Ristorante Da Vinci", "Cafe Italiano", "Chiquito", "Hummus House", "Mister M's Tradition Fish & Chips", "Ate Til Ate"}, "Lunch":{"A.G.G African Restaurant & Bar", "Anedo Finger Licking Restaurant & Bar", "Chi Bar", "Turmeric Gold", "The Spon Gate", "Nima's", "Rixs Bombay cafe bar", "The Ocean", "Cafe Rouge", "Millie's Kitchen", "Rising Cafe - From the Rubble", "The Old Crown", "Miller and Carter", "Horse and Jockey", "Ristorante Da Vinci", "Cafe Italiano", "Etna", "Las Iguanas", "Selmina's Restaurant and Bar", "Chiquito", "Hummus House UK", "Anatalya Restaurant", "Pasha Turkey Restaurant", "Mister M's Traditional Fish & Chips", "Ate Til Ate", "City Chippy", "Al Bader"}, "Dinner":{"A.G.G African Restaurant & Bar", "Anedo Finger Licking Restaurant & Bar", "Chi Bar", "Turmeric Gold", "The Spon Gate", "Nima's", "Rixs Bombay cafe bar", "The Ocean", "Cafe Rouge", "Millie's Kitchen", "Rising Cafe - From the Rubble", "The Old Crown", "Miller and Carter", "Horse and Jockey", "Ristorante Da Vinci", "Cafe Italiano", "Etna", "Las Iguanas", "Selmina's Restaurant and Bar", "Chiquito", "Hummus House UK", "Anatalya Restaurant", "Pasha Turkey Restaurant", "Mister M's Traditional Fish & Chips", "City Chippy", "My Dhabba", "Aqua", "Al Bader", "Habibi"}}
priceList = {"cheap eats":{"A.G.G African Restaurant & Bar", "Anedo Finger Licking Restaurant & Bar", "Chi Bar", "The Spon Gate", "Nima's", "Rixs Bombay cafe bar", "Millie's Kitchen", "Rising Cafe - From the Rubble", "Miller and Carter", "Cafe Italiano", "Etna", "Selmina's Restaurant and Bar", "Hummus House UK", "Pasha Turkey Restaurant", "Mister M's Traditional Fish & Chips", "Ate Til Ate", "City Chippy"}, "mid range":{"My Dhabba", "The Old Crown", "Miller and Carter", "Etna", "Las Iguanas", "Selmina's Restaurant and Bar", "Chiquito", "Anatalya Restaurant", "Turmeric Gold", "Aqua", "Al Bader", "Wagamama", "Habibi"}, "fine dining":{"Ristorante Da Vinci", "The Cross at KenilWorth"}}
cuisineList = {"African":{"A.G.G African Restaurant & Bar", "Anedo Finger Licking Restaurant & Bar"}, "British": {"Rising Cafe - From the Rubble", "The Old Crown", "Miller and Carter", "Horse and Jockey"}, "Chinese":{"Chi Bar"}, "French":{"Cafe Rouge", "Millie's Kitchen"}, "Fast Food":{"Mister M's Traditional Fish & Chips", "Ate Til Ate", "City Chippy"}, "Indian":{"The Spon Gate", "Nima's", "Rixs Bombay Cafe Bar", "The Ocean"}, "Italian":{"Ristorante Da Vinci", "Cafe Italiano", "Etna"}, "Japanese":{"Chi Bar", "Wagamama"}, "Korean":{"Jinseon Korean BBQ Restaurant & Bar"}, "Lebanese":{"Aqua", "Al Bader", "Habibi", "Hummus House UK"}, "Mexican":{"Las Iguanas", "Selmina's Restaurant Bar", "Chiquito"}, "Turkish":{"Hummus House UK", "Anatalya Restaurant", "Pasha Turkish Restaurant"}}
addressList = {"A.G.G African Restaurant & Bar":"58 Far Gosford Street, CV1 5DZ", "Anedo Finger Licking Restaurant & Bar":"80 Far Gosford Street, CV1 5DZ", "Chi Bar":"13 High Street, Coventry, CV1 5RE", "Turmeric Gold":"166 Spon St, Coventry, CV1 3BB", "The Spon Gate":"The Sky Dome, Coventry CV1 3AZ", "Nima's":"525 Foleshill Road, Coventry CV6 5AU", "Rixs Bombay cafe bar":"5 Priory Place | City Centre,CV1 5SQ", "The Ocean":"46 Jubilee Crescent | Radford, CV6 3ET", "Cafe Rouge":"2 Belgrade Plaza, CV1 4AJ", "Millie's Kitchen":"Market Way, CV1 1DL", "Rising Cafe - From the Rubble":"Priory Street, Coventry CV1 5FB,", "The Old Crown":"466 Aldermans Green Road, Coventry CV2 1NP", "Miller and Carter":"294 Kenpas Highway, Coventry CV3 6PB", "Horse and Jockey":"Tamworth Road | Corley, Coventry CV7 8AA", "Ristorante Da Vinci":"48 Earlsdon Street, Coventry CV5 6EJ", "Cafe Italiano":"2 Trinity Street, Coventry", "Etna":"54-57 Hertford Street, CV1 1LB", "Las Iguanas":"Cathedral Lanes | Broadgate, Coventry CV1 1LL", "Selmina's Restaurant and Bar":"16 Spon Street, Coventry CV1 3BA, England", "Chiquito":"Arena Retail Park Classic Drive, CV6 6AS", "Hummus House UK":"2 Market Way, Coventry CV1 1DY,", "Anatalya Restaurant":"124-126 Walsgrave Road, Coventry CV2 4AX", "Pasha Turkey Restaurant":"136 Far Gosford Street, Coventry CV1 5DY", "Mister M's Traditional Fish & Chips":"164 The Chesils | Cheylesmore, CV3 5BH", "Ate Til Ate":"87 Moseley Avenue | Coundon, CV6 1HR", "City Chippy":"3a Fairfax Street, Coventry CV1 5SR","My Dhabba":"1-3 Lower Holyhead Road, Coventry CV1 3AX", "Al Bader":"31 High Street, Coventry CV1 5RE", "Aqua":"14 Butts, Coventry 3GR", "Habibi":"142 Far Gosford Street, Coventry CV1 5DY"}
ratingList = {1:{"Rixs Bombay cafe bar", "Chiquito"}, 2:{"A.G.G African Restaurant & Bar", "Anedo Finger Licking Restaurant & Bar", "The Spon Gate", "Nima's", "Cafe Rouge", "The Old Crown", "Miller and Carter", "Horse and Jockey", "Cafe Italiano", "Etna", "Las Iguanas", "Anatalya Restaurant", "Pasha Turkish Restaurant", "Mister M's Traditional Fish & Chips", "Ate Til Ate", "My Dhabba", "Turmeric Gold", "Chi Bar", "Wagamama", "Aqua", "Al Bader", "Habibi"}, 3:{"The Ocean", "Millie's Kitchen", "Rising Cafe - From the Rubble", "Ristorante Da Vinci", "Selmina's Restaurant", "Hummus House UK"}}

def mainCode(mealChoice, cuisineChoice, priceMatters, ratingMatters, priceChoice, ratingChoice):
    """Code to use a user's preference and produce a list of restaurants with the user's preferences"""
    userMealList = mealList[mealDict[mealChoice]]
    userCuisineList = cuisineList[cuisineDict[cuisineChoice]]
    finalList = {}
    tempList = userCuisineList.intersection(userMealList) #List to save the restaurants that meet the user's meal and cuisine preferences
    if priceMatters == "no" and ratingMatters == "no":
        finalList = tempList 
    elif priceMatters == "yes" and ratingMatters == "no":
        userPriceList = priceList[priceChoice]
        finalList = userPriceList.intersection(tempList)
    elif priceMatters == "no" and ratingMatters == "yes":
        userRatingList = ratingList[ratingChoice]
        finalList = userRatingList.intersection(tempList)
    elif priceMatters == "yes" and ratingMatters == "yes":
        userRatingList = ratingList[ratingChoice]
        userPriceList = priceList[priceChoice]
        tempFinalList = userPriceList.intersection(userRatingList)
        finalList = tempFinalList.intersection(tempList)
    return finalList



